// In-game DECORATION EDITOR for Adventure City (Day 8-1) Layer 1.
//
// Mark wanted to place individual decorative pieces (lamp posts,
// signs, benches, crosswalks, vines, café patios, hanging neon signs,
// tree branches) on the foreground layer. The procedural placement
// was stripped in v0.67; this editor maintains a per-stage array
// stored in SDD.cyberDecor[key] and persisted to
// js/cyber_decor_<d>_<s>.js via the File System Access API.
//
// Usage:
//   1. Menu -> DECOR EDITOR (TEMP button, dev only)
//   2. Bottom toolbar picks the kind to place
//   3. Tap/click the play area to add a new decoration
//   4. Tap an existing piece to select it; drag to move; press
//      DELETE / Backspace to remove
//   5. Press CTRL/CMD+S or tap SAVE to write
//      js/cyber_decor_<d>_<s>.js back out (FSAPI on desktop Chrome /
//      Edge; falls back to a download otherwise)
//   6. Test the result by jumping into ADVENTURE CITY (TEST) from
//      the main menu - the decorations show up on Layer 1
//
// Like js/editor.js this is dev-kit only. To strip for public
// release: delete this file + its <script> tag + the menu entry.
window.SDD = window.SDD || {};

(function () {
  var SDD = window.SDD;
  if (!SDD.scenes) return;

  // ---- Kind metadata (matches DECOR_KINDS in scenes.js) ----------
  // Each entry defines the toolbar label + the default snap point
  // (where the decoration sits relative to the road).
  // thumb: { x, y } anchor in the 96x64 catalog thumbnail canvas so
  // each piece's painter renders fully inside the swatch.
  var KINDS = [
    { id: 'lamp',        label: 'LAMP',    snapY: 172, variants: 1, thumb: { x: 44, y: 54 } },
    { id: 'bench',       label: 'BENCH',   snapY: 172, variants: 1, thumb: { x: 30, y: 52 } },
    { id: 'sign',        label: 'SIGN',    snapY: 172, variants: 4, thumb: { x: 28, y: 56 } },
    { id: 'crosswalk',   label: 'CROSS',   snapY: 172, variants: 1, thumb: { x: 26, y: 28 } },
    { id: 'vine',        label: 'VINE',    snapY: 60,  variants: 2, thumb: { x: 48, y: 8  } },
    { id: 'cafe',        label: 'CAFE',    snapY: 144, variants: 1, thumb: { x: 24, y: 50 } },
    { id: 'hangingSign', label: 'NEON',    snapY: 40,  variants: 5, thumb: { x: 48, y: 14 } },
    { id: 'branch',      label: 'BRANCH',  snapY: 60,  variants: 4, thumb: { x: 14, y: 22 } }
  ];

  // Render one kind/variant into a small thumbnail canvas using the
  // live single-piece painter exposed by scenes.js.
  function makeThumb(kind, variant) {
    var W = 96, H = 64;
    var c = document.createElement('canvas');
    c.width = W; c.height = H;
    var g = c.getContext('2d');
    // Soft checker so transparent pieces still read.
    g.fillStyle = '#11162a'; g.fillRect(0, 0, W, H);
    g.fillStyle = '#1a2238';
    for (var yy = 0; yy < H; yy += 8) {
      for (var xx = 0; xx < W; xx += 8) {
        if (((xx + yy) / 8) % 2 === 0) g.fillRect(xx, yy, 8, 8);
      }
    }
    // Ground line for road-level pieces.
    var def = KINDS.filter(function (k) { return k.id === kind; })[0];
    if (def && def.snapY >= 144) {
      g.fillStyle = '#3a3640'; g.fillRect(0, def.id === 'cafe' ? 53 : 55, W, H);
    }
    var a = def ? def.thumb : { x: 48, y: 40 };
    if (SDD._paintDecorPiece) {
      var d = { kind: kind, x: 0, y: 0, variant: variant | 0,
                len: kind === 'vine' ? 32 : undefined,
                seed: 0x1234 };
      SDD._paintDecorPiece(g, kind, a.x, a.y, variant | 0, 0, d);
    }
    return c;
  }

  // ---- Editor state ----------------------------------------------
  var state = null;

  function go(name, data) { SDD.setScene(name, data); }

  function ensureSlot(key) {
    SDD.cyberDecor = SDD.cyberDecor || {};
    if (!SDD.cyberDecor[key]) SDD.cyberDecor[key] = [];
    return SDD.cyberDecor[key];
  }

  // ---- Save (FSAPI / fallback download) ---------------------------
  function serialize(key, list) {
    var lines = ['// Auto-generated by decor_editor.js - safe to overwrite from the editor.',
                 '// See js/cyber_decor_8_1.js comment block for the schema.',
                 'window.SDD = window.SDD || {};',
                 'SDD.cyberDecor = SDD.cyberDecor || {};',
                 'SDD.cyberDecor[\'' + key + '\'] = ['];
    for (var i = 0; i < list.length; i++) {
      var d = list[i];
      var parts = ['type:\'unused\''];  // placeholder; build proper JSON below
      var props = ['kind:\'' + d.kind + '\'', 'x:' + (d.x | 0), 'y:' + (d.y | 0)];
      if (d.variant != null) props.push('variant:' + (d.variant | 0));
      if (d.len     != null) props.push('len:'     + (d.len     | 0));
      if (d.seed    != null) props.push('seed:'    + (d.seed    | 0));
      lines.push('  { ' + props.join(', ') + ' }' + (i < list.length - 1 ? ',' : ''));
    }
    lines.push('];', '');
    return lines.join('\n');
  }
  function downloadAs(name, src) {
    var blob = new Blob([src], { type: 'text/javascript' });
    var url = URL.createObjectURL(blob);
    var a = document.createElement('a');
    a.href = url; a.download = name;
    document.body.appendChild(a); a.click(); document.body.removeChild(a);
    URL.revokeObjectURL(url);
  }
  function writeHandle(handle, src) {
    return handle.createWritable().then(function (w) {
      return w.write(src).then(function () { return w.close(); });
    });
  }
  var fileHandles = {};
  function save() {
    if (!state) return;
    var key = state.key;
    var fname = 'cyber_decor_' + state.day + '_' + state.stage + '.js';
    var src = serialize(key, state.list);
    var handle = fileHandles[key];
    var supportsFSAPI = typeof window.showSaveFilePicker === 'function';
    if (!handle && supportsFSAPI) {
      window.showSaveFilePicker({
        suggestedName: fname,
        types: [{ description: 'JavaScript', accept: { 'text/javascript': ['.js'] } }]
      }).then(function (h) {
        fileHandles[key] = h;
        writeHandle(h, src).then(function () { state.toast = 'Saved ' + fname; state.toastT = 90; });
      }).catch(function () {
        downloadAs(fname, src);
        state.toast = 'Downloaded ' + fname; state.toastT = 90;
      });
    } else if (handle) {
      writeHandle(handle, src).then(function () { state.toast = 'Saved ' + fname; state.toastT = 90; });
    } else {
      downloadAs(fname, src);
      state.toast = 'Downloaded ' + fname; state.toastT = 90;
    }
  }

  // ---- DOM overlay (toolbar + buttons) ---------------------------
  var ui = null;
  function buildUI() {
    if (ui) return ui;
    ui = document.createElement('div');
    ui.id = 'decor-editor-ui';
    ui.style.cssText = [
      'position:fixed', 'left:0', 'right:0', 'bottom:0', 'z-index:200',
      'background:rgba(15,18,32,0.92)', 'color:#fff',
      'font-family:system-ui,sans-serif', 'font-size:12px',
      'padding:6px 8px',
      'display:flex', 'flex-wrap:wrap', 'align-items:center',
      'gap:6px', 'pointer-events:auto',
      'border-top:1.5px solid #ffd23a'
    ].join(';');
    var btnCSS = 'background:rgba(255,255,255,0.10);color:#fff;border:1px solid rgba(255,255,255,0.30);padding:6px 10px;cursor:pointer;font:inherit;border-radius:4px;';
    var activeCSS = 'background:#ffd23a;color:#1a1a2a;border-color:#ffd23a;';
    // v0.76: kind selection moved to the CATALOG side panel (built
    // separately in buildCatalog). The bottom bar is now actions only.
    var btns = {};
    var hintLbl = document.createElement('span');
    hintLbl.textContent = 'PICK FROM CATALOG →   TAP MAP TO PLACE';
    hintLbl.style.cssText = 'color:#9aeaff;font-size:11px;';
    ui.appendChild(hintLbl);
    var spacer = document.createElement('span');
    spacer.style.cssText = 'flex:1';
    ui.appendChild(spacer);
    var varBtn = document.createElement('button');
    varBtn.style.cssText = btnCSS;
    varBtn.addEventListener('click', function () {
      var def = KINDS.filter(function (k) { return k.id === state.kind; })[0];
      if (!def) return;
      state.variant = ((state.variant | 0) + 1) % def.variants;
      refreshUI();
    });
    ui.appendChild(varBtn);
    var delBtn = document.createElement('button');
    delBtn.textContent = 'DELETE';
    delBtn.style.cssText = btnCSS;
    delBtn.addEventListener('click', function () { deleteSelected(); });
    ui.appendChild(delBtn);
    // v0.75: TEST button - jumps into the live level scene so Mark
    // can see the decor placements with cars, foreground, gameplay,
    // etc. Same as the level editor's test mode. Sets a flag so the
    // BACK button (pause) returns here instead of the menu.
    var testBtn = document.createElement('button');
    testBtn.textContent = 'TEST';
    testBtn.style.cssText = btnCSS + 'background:#3aff60;color:#1a1a2a;border-color:#3aff60;';
    testBtn.addEventListener('click', function () {
      state.testReturning = true;
      go('level', { day: state.day, stage: state.stage });
    });
    ui.appendChild(testBtn);
    var saveBtn = document.createElement('button');
    saveBtn.textContent = 'SAVE';
    saveBtn.style.cssText = btnCSS + 'background:#5af0ff;color:#1a1a2a;border-color:#5af0ff;';
    saveBtn.addEventListener('click', save);
    ui.appendChild(saveBtn);
    var backBtn = document.createElement('button');
    backBtn.textContent = 'EXIT';
    backBtn.style.cssText = btnCSS;
    backBtn.addEventListener('click', function () { go('menu'); });
    ui.appendChild(backBtn);
    function refreshUI() {
      var def = KINDS.filter(function (kk) { return kk.id === state.kind; })[0];
      varBtn.textContent = 'VAR ' + ((state.variant | 0) + 1) + '/' + (def ? def.variants : 1);
      if (catalog && catalog._refresh) catalog._refresh();
    }
    ui._refresh = refreshUI;
    return ui;
  }

  // ---- CATALOG side panel (v0.76) --------------------------------
  // Right-side scrollable panel showing a live thumbnail of every
  // decor kind. Clicking a thumbnail selects that kind for placing.
  // The selected kind's variant cycles via the VAR button in the
  // bottom bar, and the thumbnail updates to match.
  var catalog = null;
  function buildCatalog() {
    if (catalog) return catalog;
    catalog = document.createElement('div');
    catalog.id = 'decor-catalog-ui';
    catalog.style.cssText = [
      'position:fixed', 'right:0', 'top:0', 'bottom:46px', 'z-index:201',
      'width:108px', 'overflow-y:auto', 'box-sizing:border-box',
      'background:rgba(12,15,28,0.94)', 'color:#fff',
      'font-family:system-ui,sans-serif', 'padding:6px 6px 12px',
      'border-left:1.5px solid #ffd23a', 'pointer-events:auto'
    ].join(';');
    var title = document.createElement('div');
    title.textContent = 'CATALOG';
    title.style.cssText = 'color:#ffd23a;font-size:12px;font-weight:700;margin-bottom:6px;text-align:center;';
    catalog.appendChild(title);
    var cells = {};
    KINDS.forEach(function (k) {
      var cell = document.createElement('div');
      cell.style.cssText = 'margin-bottom:6px;cursor:pointer;border:1.5px solid transparent;border-radius:5px;padding:3px;text-align:center;';
      var thumbImg = document.createElement('canvas');
      thumbImg.width = 96; thumbImg.height = 64;
      thumbImg.style.cssText = 'width:90px;height:60px;display:block;image-rendering:pixelated;border-radius:3px;';
      cell.appendChild(thumbImg);
      var lbl = document.createElement('div');
      lbl.textContent = k.label;
      lbl.style.cssText = 'font-size:10px;color:#cfe0ff;margin-top:2px;';
      cell.appendChild(lbl);
      cell.addEventListener('click', function () {
        state.kind = k.id;
        state.variant = 0;
        if (ui && ui._refresh) ui._refresh();
      });
      cells[k.id] = { cell: cell, canvas: thumbImg };
      catalog.appendChild(cell);
    });
    function refreshCatalog() {
      KINDS.forEach(function (k) {
        var c = cells[k.id];
        if (!c) return;
        var sel = state && state.kind === k.id;
        c.cell.style.borderColor = sel ? '#ffd23a' : 'transparent';
        c.cell.style.background = sel ? 'rgba(255,210,58,0.12)' : 'transparent';
        // Render thumb (selected kind shows the active variant).
        var vv = sel ? (state.variant | 0) : 0;
        var thumb = makeThumb(k.id, vv);
        var g = c.canvas.getContext('2d');
        g.clearRect(0, 0, 96, 64);
        g.drawImage(thumb, 0, 0);
      });
    }
    catalog._refresh = refreshCatalog;
    return catalog;
  }

  function showUI() {
    if (!ui) buildUI();
    if (ui.parentNode !== document.body) document.body.appendChild(ui);
    if (!catalog) buildCatalog();
    if (catalog.parentNode !== document.body) document.body.appendChild(catalog);
    if (ui._refresh) ui._refresh();
  }
  function hideUI() {
    if (ui && ui.parentNode) ui.parentNode.removeChild(ui);
    if (catalog && catalog.parentNode) catalog.parentNode.removeChild(catalog);
  }

  function deleteSelected() {
    if (!state || state.selected < 0) return;
    state.list.splice(state.selected, 1);
    state.selected = -1;
  }

  // ---- Pointer / keyboard handling ------------------------------
  // The canvas is rendered at 3x scale (320x180 world -> 960x540
  // screen). Convert clientX/clientY -> world coords using the
  // canvas bounding rect.
  function clientToWorld(e) {
    var cv = document.getElementById('game');
    if (!cv) return null;
    var rect = cv.getBoundingClientRect();
    var scaleX = cv.width  / rect.width;
    var scaleY = cv.height / rect.height;
    var sx = (e.clientX - rect.left) * scaleX / 3;
    var sy = (e.clientY - rect.top)  * scaleY / 3;
    if (sx < 0 || sx > 320 || sy < 0 || sy > 180) return null;
    return { sx: sx, sy: sy };
  }
  function worldFromScreen(s) {
    if (!state || !s) return null;
    return { x: s.sx + state.cam.x, y: s.sy + state.cam.y };
  }
  function hitTest(wx, wy) {
    if (!state) return -1;
    // Iterate top-down (last drawn = topmost = first hit).
    for (var i = state.list.length - 1; i >= 0; i--) {
      var d = state.list[i];
      var dx = wx - d.x, dy = wy - d.y;
      // Generous square hitbox (16x16) - decor pieces are small.
      if (dx > -10 && dx < 18 && dy > -22 && dy < 14) return i;
    }
    return -1;
  }

  var pointerDown = false;
  function onPointerDown(e) {
    if (!state) return;
    var s = clientToWorld(e);
    if (!s) return;
    if (s.sy > 142) return;     // tap inside the toolbar's vertical range cancelled by UI
    e.preventDefault();
    var w = worldFromScreen(s);
    var hit = hitTest(w.x, w.y);
    pointerDown = true;
    if (hit >= 0) {
      state.selected = hit;
      state.dragging = hit;
      state.dragOff = { x: w.x - state.list[hit].x, y: w.y - state.list[hit].y };
    } else {
      // Place a new piece at the touch point. Ground-level kinds
      // (lamp/bench/sign/crosswalk) always snap to the road plane so
      // the user can tap anywhere in the lower screen and the piece
      // lands correctly. Hanging kinds (vine/hangingSign/branch) and
      // mid-height (cafe) keep the raw Y so they can go on facades.
      var def = KINDS.filter(function (k) { return k.id === state.kind; })[0];
      var snapY = (def && def.snapY) || 172;
      var alwaysSnap = (state.kind === 'lamp' || state.kind === 'bench' ||
                        state.kind === 'sign' || state.kind === 'crosswalk');
      var py = alwaysSnap ? snapY
             : (Math.abs(w.y - snapY) < 24) ? snapY
             : (w.y | 0);
      var entry = { kind: state.kind, x: w.x | 0, y: py, variant: state.variant | 0 };
      if (state.kind === 'vine')   entry.len = 18;
      if (state.kind === 'cafe' || state.kind === 'branch') entry.seed = (Math.random() * 0x10000) | 0;
      state.list.push(entry);
      state.selected = state.list.length - 1;
      state.dragging = state.selected;
      state.dragOff = { x: 0, y: 0 };
    }
  }
  function onPointerMove(e) {
    if (!state || !pointerDown || state.dragging < 0) return;
    var s = clientToWorld(e);
    if (!s) return;
    var w = worldFromScreen(s);
    var d = state.list[state.dragging];
    if (!d) return;
    d.x = (w.x - state.dragOff.x) | 0;
    d.y = (w.y - state.dragOff.y) | 0;
  }
  function onPointerUp() {
    pointerDown = false;
    if (state) state.dragging = -1;
  }
  function onKey(e) {
    if (!state) return;
    if (e.key === 'Backspace' || e.key === 'Delete') {
      e.preventDefault();
      deleteSelected();
    } else if (e.key === 's' && (e.ctrlKey || e.metaKey)) {
      e.preventDefault();
      save();
    } else if (e.key === 'ArrowLeft')  { state.cam.x = Math.max(0, state.cam.x - 32); }
    else if (e.key === 'ArrowRight') { state.cam.x = Math.min(state.maxCamX, state.cam.x + 32); }
    else if (e.key === 'ArrowUp')    { state.cam.y = Math.max(0, state.cam.y - 16); }
    else if (e.key === 'ArrowDown')  { state.cam.y = Math.min(state.maxCamY, state.cam.y + 16); }
    else if (e.key >= '1' && e.key <= '9') {
      var idx = (e.key | 0) - 1;
      if (idx < KINDS.length) {
        state.kind = KINDS[idx].id;
        state.variant = 0;
        if (ui && ui._refresh) ui._refresh();
      }
    }
  }
  var pointerListenersBound = false;
  function bindPointer() {
    if (pointerListenersBound) return;
    var cv = document.getElementById('game');
    if (!cv) return;
    cv.addEventListener('pointerdown', onPointerDown);
    window.addEventListener('pointermove', onPointerMove);
    window.addEventListener('pointerup',   onPointerUp);
    window.addEventListener('pointercancel', onPointerUp);
    window.addEventListener('keydown', onKey);
    pointerListenersBound = true;
  }
  function unbindPointer() {
    if (!pointerListenersBound) return;
    var cv = document.getElementById('game');
    if (cv) cv.removeEventListener('pointerdown', onPointerDown);
    window.removeEventListener('pointermove', onPointerMove);
    window.removeEventListener('pointerup',   onPointerUp);
    window.removeEventListener('pointercancel', onPointerUp);
    window.removeEventListener('keydown', onKey);
    pointerListenersBound = false;
  }

  // ---- Scene -----------------------------------------------------
  SDD.scenes.decorEdit = {
    enter: function (d) {
      var day   = (d && d.day)   || 8;
      var stage = (d && d.stage) || 1;
      // v0.76: expose day + stage on the scene object itself so the
      // _cyDrawDecor renderer (which keys on SDD.scene.day +
      // SDD.scene.stage) finds the right per-stage decor array.
      // Without this the editor's preview + the in-game decor both
      // come back empty - Mark's "I can't see it when I try it" bug.
      this.day = day;
      this.stage = stage;
      var key   = day + '-' + stage;
      var level = SDD.levels && SDD.levels[key];
      var T = (SDD.engine && SDD.engine.TILE) || 16;
      state = {
        day: day, stage: stage, key: key,
        list: ensureSlot(key),
        kind: 'lamp',
        variant: 0,
        selected: -1,
        dragging: -1,
        dragOff: { x: 0, y: 0 },
        cam: { x: 0, y: 44 },
        maxCamX: level ? Math.max(0, level.width  * T - 320) : 0,
        maxCamY: level ? Math.max(0, level.height * T - 180) : 0,
        t: 0,
        toast: '', toastT: 0
      };
      showUI();
      bindPointer();
      if (SDD.audio && SDD.audio.stopMusic) SDD.audio.stopMusic();
    },
    exit: function () {
      unbindPointer();
      hideUI();
      state = null;
    },
    update: function () {
      if (!state) return;
      state.t++;
      if (state.toastT > 0) state.toastT--;
      // Hold-arrow scrolling for desktop convenience (browser key
      // repeat is the main path; this just lets pad/touch use the
      // SDD input system instead).
      var In = SDD.input;
      if (In) {
        if (In.held('left'))  state.cam.x = Math.max(0, state.cam.x - 4);
        if (In.held('right')) state.cam.x = Math.min(state.maxCamX, state.cam.x + 4);
        if (In.held('up'))    state.cam.y = Math.max(0, state.cam.y - 2);
        if (In.held('down'))  state.cam.y = Math.min(state.maxCamY, state.cam.y + 2);
        if (In.pressed('pause')) { go('menu'); return; }
      }
    },
    render: function (g) {
      if (!state) return;
      var camx = state.cam.x | 0;
      var camy = state.cam.y | 0;
      // Paint the cyber background using the live painters.
      var sky = SDD.cyDebug;   // unused but reserved
      var cyDraw = SDD.scenes.level && null;   // we re-use module fns
      // The drawSky_cyber + drawForeground_cyber are file-scope in
      // scenes.js. We reach them through the THEMES + FOREGROUNDS
      // registries that scenes.js exposes via the level scene -
      // simpler to render the level's tiles + background using a
      // minimal proxy on the scene.
      // For preview purposes, just call drawSky_cyber via the
      // theme registry: SDD.themesProxy is set up below in
      // scenes.js if needed; for now read directly.
      if (SDD._drawSkyCyber) SDD._drawSkyCyber(g, camx, camy, 0, state.t);

      // Draw the level tiles for context (so the player can see
      // where the road / sky / shop row sits).
      var lvl = SDD.levels && SDD.levels[state.key];
      var S = SDD.sprites;
      if (lvl && S) {
        var T = SDD.engine.TILE;
        var t0x = Math.max(0, Math.floor(camx / T));
        var t1x = Math.min(lvl.width - 1, Math.ceil((camx + 320) / T));
        var t0y = Math.max(0, Math.floor(camy / T));
        var t1y = Math.min(lvl.height - 1, Math.ceil((camy + 180) / T));
        for (var ty = t0y; ty <= t1y; ty++) {
          for (var tx = t0x; tx <= t1x; tx++) {
            var ch = (lvl.tiles[ty] && lvl.tiles[ty][tx]) || ' ';
            var name = null;
            if (ch === 'X') {
              var aboveSolid = (ty > 0) && (lvl.tiles[ty - 1] && lvl.tiles[ty - 1][tx] === 'X');
              var base = aboveSolid ? 'tile_dirt' : 'tile_ground';
              name = (S.get(base + '_cyber')) ? base + '_cyber' : base;
            }
            if (name) {
              var img = S.get(name);
              if (img) g.drawImage(img, tx * T - camx, ty * T - camy);
            }
          }
        }
      }

      // Draw the foreground decorations (so the editor preview
      // matches what the player sees).
      if (SDD._drawDecor) SDD._drawDecor(g, camx, camy, state.t);

      // Editor overlay: selection highlight on the active piece.
      if (state.selected >= 0 && state.selected < state.list.length) {
        var d = state.list[state.selected];
        var sx = (d.x | 0) - camx;
        var sy = (d.y | 0) - camy;
        g.save();
        g.strokeStyle = '#ffd23a';
        g.lineWidth = 1;
        g.strokeRect(sx - 10, sy - 22, 28, 36);
        g.fillStyle = 'rgba(255,210,58,0.20)';
        g.fillRect(sx - 10, sy - 22, 28, 36);
        g.restore();
      }

      // Top-left status bar.
      var text = SDD.sprites.text;
      text(g, 'DECOR EDITOR  ' + state.key, 4, 4, '#ffd23a', 1, 'left');
      text(g, 'KIND: ' + state.kind.toUpperCase() + '  VAR: ' + (state.variant + 1), 4, 14, '#9aeaff', 1, 'left');
      text(g, 'CAM: ' + camx + ',' + camy, 4, 24, '#9aeaff', 1, 'left');
      text(g, 'COUNT: ' + state.list.length, 4, 34, '#9aeaff', 1, 'left');
      if (state.toastT > 0) {
        text(g, state.toast, 160, 24, '#ffd23a', 1, 'center');
      }
      text(g, 'TAP = PLACE  DRAG = MOVE  DEL = REMOVE', 160, 170, '#aaa', 1, 'center');
    }
  };

  // ---- Expose painters from scenes.js for use here ----------------
  // scenes.js sets SDD._drawSkyCyber + SDD._drawDecor so this
  // standalone editor scene can render the live cyber background +
  // decorations without depending on the level scene.
})();
